AdcsAuthorityInformationAccess: Always makes a change #128, #138
dsccommunity/ActiveDirectoryCSDsc pull request #141
Opened 2024-04-18 15:09 UTC by dan-hughes

#### Pull Request (PR) description
Removed the `AllowRestartService` parameter from being tested/compared.
Updated `Get-CaAiaUriList` to force a `System.String[]` to be returned regardless of single or multiple values.

#### This Pull Request (PR) fixes the following issues
- Fixes #128 
- Fixes #138

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141)

2024-04-21 06:55 UTC, johlju requested changes
> On tests, I'd need to possibly have mocks with only single AIA and OCSP values in to begin with. Thoughts?

I think we should test that no value (`null`?), single value, and multiple values are returned. :thinking: 

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-:-NvzOuTuD5AQxXRdd8bt:b6x595c)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @dan-hughes and @PlagueHO)

___
*[`source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1` line 37 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-NvzQgV189MistNq4sHw:-NvzQgV189MistNq4sHx:bm4cto0) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/522b55340deb89661d05f78c3b191b37df1e22b1/source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1#L37)):*
> ```PowerShell
>         IsSingleInstance = 'Yes'
>         AiaUri = Get-CaAiaUriList -ExtensionType 'AddToCertificateAia'
>         OcspUri = Get-CaAiaUriList -ExtensionType 'AddToCertificateOcsp'
> ```

We should check if `Get-CaAiaUriList` is null or empty, if it is not we should cast the value to an string array - otherwise we return $null.

Same for both values. Also see other comment.
___
*[`source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1` line 209 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-NvzQ2fJ0hWj2iIFoxQ9:-NvzQ2fKDjQTaHy8SH3i:b7cfn0p) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/522b55340deb89661d05f78c3b191b37df1e22b1/source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1#L209)):*
> ```PowerShell
>     $null = $PSBoundParameters.Remove('IsSingleInstance')
>     $null = $PSBoundParameters.Remove('AllowRestartService')
> ```

We should tell `Test-DscParameterState` to exclude the parameter from testing instead of removing it (as is also added to the return value of Get-TargetResource). There should be a parameter for that in the command. 
___
*[`source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1` line 239 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-NvzPK-e0UZhQcyZHMR_:-NvzPK-e0UZhQcyZHMRa:b-q5alm1) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/522b55340deb89661d05f78c3b191b37df1e22b1/source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1#L239)):*
> ```PowerShell
> 
>     $UriList = [System.String[]] (Get-CAAuthorityInformationAccess | Where-Object -Property $ExtensionType -Eq $true).Uri
>     return ,$UriList
> ```

I think we should avoid the unary operator. I think it is better to cast the returned value in the next step instead to make sure we actually get a string array unless it returns `$null`.


<!-- Sent from Reviewable.io -->

2024-04-21 12:33 UTC, dan-hughes reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1` line 209 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-NvzQ2fJ0hWj2iIFoxQ9:-Nw-_6Nj9Cx5tPZ0xIq8:b4aioec) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/522b55340deb89661d05f78c3b191b37df1e22b1/source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1#L209)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should tell `Test-DscParameterState` to exclude the parameter from testing instead of removing it (as is also added to the return value of Get-TargetResource). There should be a parameter for that in the command.
</blockquote></details>

That's a nicer solution. I'm assuming the ```IsSingleInstance``` parameter needs to go into the exclude too?
___
*[`source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1` line 239 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-NvzPK-e0UZhQcyZHMR_:-Nw-_UDe5XYSB8uNMNp7:b-86ym4x) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/522b55340deb89661d05f78c3b191b37df1e22b1/source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1#L239)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think we should avoid the unary operator. I think it is better to cast the returned value in the next step instead to make sure we actually get a string array unless it returns `$null`.
</blockquote></details>

This function returns ```$null```, ```System.String[]``` or ```System.String``` if the call to ```Get-CAAuthorityInformationAccess``` is a single value.

Would it be 'cleaner' to ensure that this function only returns ```$null``` or ```System.String[]```? 

Or is the checking logic explicitly required to work around this behaviour?


<!-- Sent from Reviewable.io -->

2024-04-22 16:43 UTC, dan-hughes reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1` line 37 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-NvzQgV189MistNq4sHw:-Nw5erqpD54LH88FqlkM:bnplux2) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/522b55340deb89661d05f78c3b191b37df1e22b1/source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should check if `Get-CaAiaUriList` is null or empty, if it is not we should cast the value to an string array - otherwise we return $null.

Same for both values. Also see other comment.
</blockquote></details>

Taking a fresh look at this ```Get-CaAiaUriList``` will never return ```System.String[]``` on it's own as PowerShell will do it's thing and unwrap the values.
If the result is cast outside as you suggested, is a ```$null``` check required as PowerShell should explicitly convert ```$null``` into an empty string in this case?
___
*[`source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1` line 239 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/141#-NvzPK-e0UZhQcyZHMR_:-Nw5flWV-4wRiTBwIyC1:b-i2znfn) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/522b55340deb89661d05f78c3b191b37df1e22b1/source/DSCResources/DSC_AdcsAuthorityInformationAccess/DSC_AdcsAuthorityInformationAccess.psm1#L239)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

This function returns ```$null```, ```System.String[]``` or ```System.String``` if the call to ```Get-CAAuthorityInformationAccess``` is a single value.

Would it be 'cleaner' to ensure that this function only returns ```$null``` or ```System.String[]```? 

Or is the checking logic explicitly required to work around this behaviour?
</blockquote></details>

As per above I'm not sure it will ever return a ```System.String[]```. Changed just to ```System.String```, is this a valid approach?


<!-- Sent from Reviewable.io -->

2024-06-01 14:01 UTC, johlju commented
If you rebase this one I continue with this one. 🙂

2024-06-01 17:41 UTC, dan-hughes commented
I really messed up when trying to merge. I think it's all back to where it should be now.

What's going to be the optimal solution for this? The `Get-CaAiaUriList` should return a `string` or `string[]`.

2024-06-11 17:41 UTC, johlju commented
I will try to get back to this soon.

2025-05-02 14:52 UTC, dasy77 commented
For me, removing the properties that should not be compared before passing it to Test-DscParameterState is the only sensible solution. It is simple and quick to implement and it has no dependencies on other functions, the adaptation of which may result in extensive code changes.

Furthermore, it makes no significant difference to me whether the function itself ensures that the return type is System.String[] or whether I do this externally when calling the function. But it is absolutely important and necessary that one of the two variants is implemented as quickly as possible.

Users have been dealing with the issues (#128, #138) for long enough now. Don't you agree?

2025-05-02 15:52 UTC, dan-hughes commented
@johlju, fixed it up for the time being. If/when it get's converted to a class a more robust solution can be utilised.

2025-05-04 08:59 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Agree, let's merge it an another PR can make it better if need be.

> Reviewed 3 of 3 files at r5, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/141#-:-OPPWBztCTmsZiqCYVI1:b9gh7x6)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2025-05-04 09:01 UTC, merged