`Tests` - Migrate to Pester 5
dsccommunity/ActiveDirectoryCSDsc pull request #144
Opened 2024-05-24 15:41 UTC by dan-hughes

#### Pull Request (PR) description

Migrate tests to Pester 5

#### This Pull Request (PR) fixes the following issues

- N/A

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2024-05-24 15:43 UTC, dan-hughes commented
I'm still working on the integration tests but I'm not sure how to run those outside of azure pipelines.

2024-05-24 21:33 UTC, dan-hughes commented
@johlju, what's going the best way to tackle this? Is there anyone else that can review? I'm expecting changes to be required, but the syntax should all be Pester 5 now.

Regarding `prefix.ps1`, how is that tested? I see you have code coverage on SqlServerDsc but I can't work out where!

I should have the integration tests complete next week.

2024-05-25 11:36 UTC, johlju commented
> Regarding prefix.ps1, how is that tested? I see you have code coverage on SqlServerDsc but I can't work out where!

I think it is covered because of classes being test which imports the built module during tests. 🤔  So it is implicitly tested. You can skip testing that file in this repo, and ignore the code coverage warnings. 

> Is there anyone else that can review? 

Unfortunately there are few in the community that helps with reviews, we need more. It is  mostly me or @PlagueHO that does reviews when we have time (me mostly on weekends in front of the TV). 

> I should have the integration tests complete next week.

Awesome!

2024-05-25 12:55 UTC, johlju requested changes
Minor comments, mostly pipeline stuff. I will continue the review later. Please check the other tests script files for similar changes.

> Reviewed 25 of 32 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-:-NyjoGS37kSHX9jp8uOj:bvxt0cw)* status: 26 of 32 files reviewed, 35 unresolved discussions (waiting on @dan-hughes)

___
*[`build.yaml` line 65 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjdpmnC-ejoG7mTM5L:-Nyjdpmo0uM0gI78y6-1:bf1mqe9) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/6e18fd301de7e621bd1ec8c77de9e091ffe2b7de/build.yaml#L65)):*
> ```YAML
>   Script:
>     - tests/Unit
>     - tests/Integration
> ```

The previous pipeline ran both unit tests and integration tests at the same time. The suggested change is to run only unit test, which is good. For example we don't want to run integration tests when we just want to make sure if we have code coverage. But, make sure azure-pipelines.yml is also updated to run integration tests as a separat job (see SqlServerDsc for inspiration).



_Code quote:_
```YAML
    - tests/Unit
    - tests/Integration
```
___
*[`build.yaml` line 120 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjbddE8bqS9XHjOtk3:-NyjbddE8bqS9XHjOtk4:bmj130i) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L120)):*
> ```YAML
>     Path: ./output/RequiredModules/DscResource.Base
>     AddToManifest: false
>     Exclude: PSGetModuleInfo.xml
> ```

This can be removed if the `ResourceBase` class is not used for class-based resources. It just adds size to the built module unnecessarily.



_Code quote:_
```YAML
  DscResource.Base:
    CopyOnly: true
    Path: ./output/RequiredModules/DscResource.Base
    AddToManifest: false
    Exclude: PSGetModuleInfo.xml
```
___
*[`build.yaml` line 144 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjc7CM2ZiDFYWE7lt4:-Nyjc7CM2ZiDFYWE7lt5:b-jsd95) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L144)):*
> ```YAML
>   ExcludeFromCodeCoverage:
>     - Modules/DscResource.Common
>     - Modules/DscResource.Base
> ```

This can be removed, see previous comment.
___
*[`build.yaml` line 168 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjcBvJE7L7CM0-iQG9:-NyjcBvJE7L7CM0-iQGA:b-jsd95) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L168)):*
> ```YAML
>     ExcludeModuleFile:
>       - Modules/DscResource.Common
>       - Modules/DscResource.Base
> ```

This can be removed, see previous comment.
___
*[`build.yaml` line 188 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyj_HGu4BlGOS7Z7bPb:-Nyj_HGu4BlGOS7Z7bPc:b-y6hw4s) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L188)):*
If we should publish the release asset here, then line 24 to run the task to package the asset need to be uncommented.  If this is removed then we can also remove the entire task `Package_WikiContent` on line 44. Either way is good.

>[!NOTE]
>It can be removed here because I added it in SqlServerDsc as a test. The task `Package_WikiContent` should instead be >moved as a task in `DscResource.DocGenerator` so it can be reused by all repos - I just haven't had the time. After that is >done Sampler plaster templates should be updated to include the required configuration to publish the release asset. But >that is several different PR's :slightly_smiling_face: 
___
*[`source/prefix.ps1` line 1 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjg4aW1cM3vh6AWdEK:-Nyjg4aX1pk7j6tjWh1c:b-mtz3nl) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/source/prefix.ps1#L1)):*
> ```PowerShell
> using module .\Modules\DscResource.Base
> ```

This is not needed unless the class `ResourceBase` is actually used by class-based resources. See previous comments.
___
*[`source/prefix.ps1` line 4 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjheOv22z7gxOqi5SZ:-NyjheOv22z7gxOqi5S_:b-82s4xw) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/source/prefix.ps1#L4)):*
> ```PowerShell
> 
> $script:dscResourceCommonModulePath = Join-Path -Path $PSScriptRoot -ChildPath 'Modules/DscResource.Common'
> Import-Module -Name $script:dscResourceCommonModulePath
> ```

This is used to load command functions for classes, private functions and public commands. If there are no such we could remove this.
___
*[`source/prefix.ps1` line 10 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjgZbF-baL47V03O9X:-NyjgZbF-baL47V03O9Y:b-ywmn8e) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/source/prefix.ps1#L10)):*
> ```PowerShell
> Import-Module -Name $script:activeDirectoryCSDscCommonModulePath
> 
> $script:localizedData = Get-LocalizedData -DefaultUICulture 'en-US'
> ```

There is no localization file in the source/en-US folder that this can load, so we could remove this. This is used to load localization strings for classes, private functions and public commands (`source/Private` and `source/Public`) - if there are no such functions this can be removed. But we can keep it here an add en empty localization string file in the 'en-US` folder so is the module prepared to use private and public. See https://github.com/dsccommunity/SqlServerDsc/blob/main/source/en-US/SqlServerDsc.strings.psd1 and an "empty file" is with no string data included.
___
*[`source/Modules/ActiveDirectoryCSDsc.Common/ActiveDirectoryCSDsc.Common.psm1` line 41 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyji7Ig090vonzMKVWQ:-Nyji7Ig090vonzMKVWR:bxy0vk0) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/6e18fd301de7e621bd1ec8c77de9e091ffe2b7de/source/Modules/ActiveDirectoryCSDsc.Common/ActiveDirectoryCSDsc.Common.psm1#L41)):*
> ```PowerShell
> Export-ModuleMember -Function @(
>     'Restart-ServiceIfExists'
> )
> ```

I think we should keep this since there are no module manifest to define what to export and not. Without this it would also export (future) private functions that isn't mean to be exported. :thinking: 



_Code quote:_
```PowerShell
Export-ModuleMember -Function @(
    'Restart-ServiceIfExists'
)
```
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 203 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjjm_Y4r0D4VWL8idU:-Nyjjm_Y4r0D4VWL8idV:b4dnmwx) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L203)):*
> ```PowerShell
>     BeforeAll {
>         Mock -CommandName Add-CAAuthorityInformationAccess `
>             -ModuleName DSC_AdcsAuthorityInformationAccess
> ```

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 225 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjk6nJCL6-hgvvjI6a:-Nyjk6nJCL6-hgvvjI6b:b4dnmwx) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L225)):*
> ```PowerShell
> 
>                 Mock -CommandName Get-TargetResource `
>                     -ModuleName DSC_AdcsAuthorityInformationAccess `
> ```

We have already set this as the default parameter f [...]

2024-05-25 12:59 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144)* status: 26 of 32 files reviewed, 34 unresolved discussions (waiting on @dan-hughes)

___
*[`build.yaml` line 65 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjdpmnC-ejoG7mTM5L:-Nyjp9Hi24w4rsjoyEix:b-ddb1eu) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/6e18fd301de7e621bd1ec8c77de9e091ffe2b7de/build.yaml#L65)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The previous pipeline ran both unit tests and integration tests at the same time. The suggested change is to run only unit test, which is good. For example we don't want to run integration tests when we just want to make sure if we have code coverage. But, make sure azure-pipelines.yml is also updated to run integration tests as a separat job (see SqlServerDsc for inspiration).
</blockquote></details>

I looked and saw that the Azure Pipeline looks good.


<!-- Sent from Reviewable.io -->

2024-05-26 09:35 UTC, johlju requested changes
> Reviewed 6 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144)* status: all files reviewed, 43 unresolved discussions (waiting on @dan-hughes)

___
*[`tests/Unit/DSC_AdcsCertificationAuthority.Tests.ps1` line 102 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyo6cQZ08k-yVcHKEdH:-Nyo6cQZ08k-yVcHKEdI:b-nbi44w) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsCertificationAuthority.Tests.ps1#L102)):*
> ```PowerShell
>     Get-Module -Name $script:dscResourceName -All | Remove-Module -Force
> 
>     #Remove-Module -Name AdcsAdministrationStub -Force
> ```

Should we remove this comment if the stub module is not necessary?
___
*[`tests/Unit/DSC_AdcsCertificationAuthoritySettings.Tests.ps1` line 197 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoBpwm5vtV9nsgDblA:-NyoBpwm5vtV9nsgDblB:b-tk301w) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsCertificationAuthoritySettings.Tests.ps1#L197)):*
> ```PowerShell
>     BeforeAll {
>         InModuleScope -Parameters @{
>             inModuleScopeParams = $baseParameterCurrentList
> ```

Reads strange if we call the parameter `inModuleScopeParams` since it is not that. It is more `baseTestParameters` or something?
___
*[`tests/Unit/DSC_AdcsCertificationAuthoritySettings.Tests.ps1` line 293 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoCimnED70ow2nxOeF:-NyoCimnED70ow2nxOeG:blm2iri) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsCertificationAuthoritySettings.Tests.ps1#L293)):*
> ```PowerShell
>         }
>     }
> ```

We can remove the extra blank line
___
*[`tests/Unit/DSC_AdcsCertificationAuthoritySettings.Tests.ps1` line 325 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoCYXE4nn9nFHi_e9N:-NyoCYXE4nn9nFHi_e9O:b-tk301w) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsCertificationAuthoritySettings.Tests.ps1#L325)):*
> ```PowerShell
>     BeforeAll {
>         InModuleScope -Parameters @{
>             inModuleScopeParams = $baseParameterCurrentList
> ```

Reads strange if we call the parameter `inModuleScopeParams` since it is not that. It is more `baseTestParameters` or something?
___
*[`tests/Unit/DSC_AdcsOnlineResponder.Tests.ps1` line 45 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoDoS_Buv-jrUQjdIj:-NyoDoS_Buv-jrUQjdIk:b-4ccnft) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsOnlineResponder.Tests.ps1#L45)):*
> ```PowerShell
> 
>     Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '..\TestHelpers\CommonTestHelper.psm1')
>     #Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '.\Stubs\AdcsAdministrationStub.psm1')
> ```

Should we remove this line if the stub module is not used?
___
*[`tests/Unit/DSC_AdcsTemplate.Tests.ps1` line 45 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoEVJQE19JqBaSULyy:-NyoEVJQE19JqBaSULyz:b-4ccnft) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsTemplate.Tests.ps1#L45)):*
> ```PowerShell
> 
>     Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '..\TestHelpers\CommonTestHelper.psm1')
>     #Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '..\TestHelpers\AdcsStub.psm1')
> ```

Should we remove this line if the stub module is not used?
___
*[`tests/Unit/DSC_AdcsTemplate.Tests.ps1` line 105 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoEip7D7FXfykBOTzQ:-NyoEipC9_cH5N7lJuET:b-4ccnft) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsTemplate.Tests.ps1#L105)):*
> ```PowerShell
>     Get-Module -Name $script:dscResourceName -All | Remove-Module -Force
> 
>     #Remove-Module -Name AdcsStub -Force
> ```

Should we remove this line if the stub module is not used?
___
*[`tests/Unit/DSC_AdcsWebEnrollment.Tests.ps1` line 45 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoF-TH8Po_cVkKarB7:-NyoF-TH8Po_cVkKarB8:b-4ccnft) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsWebEnrollment.Tests.ps1#L45)):*
> ```PowerShell
> 
>     Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '..\TestHelpers\CommonTestHelper.psm1')
>     #Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '.\Stubs\AdcsAdministrationStub.psm1')
> ```

Should we remove this line if the stub module is not used?
___
*[`tests/Unit/DSC_AdcsWebEnrollment.Tests.ps1` line 100 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyoF48u5DAyf2Fs3EVA:-NyoF48u5DAyf2Fs3EVB:b-4ccnft) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsWebEnrollment.Tests.ps1#L100)):*
> ```PowerShell
>     Get-Module -Name $script:dscResourceName -All | Remove-Module -Force
> 
>     #Remove-Module -Name AdcsAdministrationStub -Force
> ```

Should we remove this line if the stub module is not used?


<!-- Sent from Reviewable.io -->

2024-05-27 11:47 UTC, dan-hughes reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144)* status: all files reviewed, 43 unresolved discussions (waiting on @johlju)

___
*[`build.yaml` line 120 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjbddE8bqS9XHjOtk3:-Nytib3C4rgGc9NQtRvo:buydxh3) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L120)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This can be removed if the `ResourceBase` class is not used for class-based resources. It just adds size to the built module unnecessarily.
</blockquote></details>

I was 'preparing' the module for class use. I suppose I should have asked what the direction is for future additions. Is it class based resources only for new resources going forward or is that something undecided?
___
*[`source/prefix.ps1` line 10 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjgZbF-baL47V03O9X:-NytiPoI-RXZReKcUmGD:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/source/prefix.ps1#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There is no localization file in the source/en-US folder that this can load, so we could remove this. This is used to load localization strings for classes, private functions and public commands (`source/Private` and `source/Public`) - if there are no such functions this can be removed. But we can keep it here an add en empty localization string file in the 'en-US` folder so is the module prepared to use private and public. See https://github.com/dsccommunity/SqlServerDsc/blob/main/source/en-US/SqlServerDsc.strings.psd1 and an "empty file" is with no string data included.
</blockquote></details>

Done.
___
*[`source/Modules/ActiveDirectoryCSDsc.Common/ActiveDirectoryCSDsc.Common.psm1` line 41 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyji7Ig090vonzMKVWQ:-NytiVBbCo-JXT8AbO9M:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/6e18fd301de7e621bd1ec8c77de9e091ffe2b7de/source/Modules/ActiveDirectoryCSDsc.Common/ActiveDirectoryCSDsc.Common.psm1#L41)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think we should keep this since there are no module manifest to define what to export and not. Without this it would also export (future) private functions that isn't mean to be exported. :thinking:
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 203 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjjm_Y4r0D4VWL8idU:-Nytk6Om6ElfG0T-KQZ2:b-2cz8n) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L203)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

I missed all of these in this file. 

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 225 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjk6nJCL6-hgvvjI6a:-Nytk6rrD-lCgC0o9zyE:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L225)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 272 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjkLGr-lOM-J1Vt40y:-Nytk7KA49baTXuiyD7W:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L272)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 324 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjkTgR1GPfNRyHplPw:-NytkCKFBPlT939iLYKu:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L324)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 376 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjkZEq4lbajUS3pK1Z:-NytkC_SDBsy_TGuyeC-:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L376)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 428 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjkcqh4xqxJFQOzS6p:-NytkCpg5JX4S8ZvpfFA:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L428)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 481 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjki1M9wcH4q48rSCP:-NytkD758_AJU2qxOX0K:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L481)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 537 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjkobn36Kx-ONpB9Lj:-NytkDORBIQ00hZyi7-t:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1#L537)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We have already set this as the default parameter for `Mock` so no need to specify `ModuleName` here. Same for the two mocks below too.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_AdcsAuthorityInformationAccess.Tests.ps1` line 596 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyjktqc4vwiePU52EMQ:-NytkDri0iUvjo-xyJqp:b-896fix) ([raw file](https://github [...]

2024-05-27 14:04 UTC, dan-hughes reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144)* status: 23 of 35 files reviewed, 43 unresolved discussions (waiting on @johlju)

___
*[`build.yaml` line 188 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyj_HGu4BlGOS7Z7bPb:-NyuLws_0ubFKV_wMxoa:b-dvcmia) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L188)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If we should publish the release asset here, then line 24 to run the task to package the asset need to be uncommented.  If this is removed then we can also remove the entire task `Package_WikiContent` on line 44. Either way is good.

>[!NOTE]
>It can be removed here because I added it in SqlServerDsc as a test. The task `Package_WikiContent` should instead be >moved as a task in `DscResource.DocGenerator` so it can be reused by all repos - I just haven't had the time. After that is >done Sampler plaster templates should be updated to include the required configuration to publish the release asset. But >that is several different PR's :slightly_smiling_face:
</blockquote></details>

Is moving `Package_WikiContent` just a lift and shift into `DscResource.DocGenerator`?

I can pick that up next or now, I'd just need some guidance that every repo/project gets updated.


<!-- Sent from Reviewable.io -->

2024-05-27 14:07 UTC, dan-hughes commented
@johlju, tidied up based on your comments. 

Just the pipeline/`build.yaml` to sort out based on whether it's worth leaving in, in preparation for class based resources?

2024-05-27 16:40 UTC, johlju requested changes
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-hughes)

___
*[`build.yaml` line 120 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjbddE8bqS9XHjOtk3:-Nyur8JU1aG5hxtHNj8O:bj79evo) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L120)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

I was 'preparing' the module for class use. I suppose I should have asked what the direction is for future additions. Is it class based resources only for new resources going forward or is that something undecided?
</blockquote></details>

Any module may have and add class-based resource (old and new). The modul [DscResource.Base](https://github.com/dsccommunity/DscResource.Base) is an opinionated way of creating class-based resource and very much still undocumented. It is not necessary to create class-based resource. But you can leave it in if you believe it will be utilized.
___
*[`build.yaml` line 188 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyj_HGu4BlGOS7Z7bPb:-NyusfK10OeYbKdn3bBR:buop2z4) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L188)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Is moving `Package_WikiContent` just a lift and shift into `DscResource.DocGenerator`?

I can pick that up next or now, I'd just need some guidance that every repo/project gets updated.
</blockquote></details>

Yes basically just create necessary task files similar to the others in `DscResource.DocGenerator`. If you have time with that please do now or later, you decide. It is only this and SqlServerDsc that uses it I think.
___
*[`source/en-US/ActiveDirectoryCSDsc.strings.psd1` line 10 at r3](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyutgfoDBuUDn3uj2Gq:-NyutgfoDBuUDn3uj2Gr:b-9yhw5i) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/6294412256f05cfc2df82dc8aa32b8ac51b8c9c0/source/en-US/ActiveDirectoryCSDsc.strings.psd1#L10)):*
> ```PowerShell
> 
> @'
> '@
> ```

I think we need this:



_Suggestion:_
```PowerShell
ConvertFrom-StringData @'
'@
```


<!-- Sent from Reviewable.io -->

2024-05-27 20:31 UTC, dan-hughes reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144)* status: all files reviewed, 7 unresolved discussions (waiting on @johlju)

___
*[`build.yaml` line 120 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjbddE8bqS9XHjOtk3:-NyvhvzS2LTn7BfsmhLM:b6kq2fv) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L120)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Any module may have and add class-based resource (old and new). The modul [DscResource.Base](https://github.com/dsccommunity/DscResource.Base) is an opinionated way of creating class-based resource and very much still undocumented. It is not necessary to create class-based resource. But you can leave it in if you believe it will be utilized.
</blockquote></details>

As it's the 'future', to me it makes sense to leave any scaffolding for class based resources in place.

Unless it's worth just leaving it there commented out to it's easy to enable?
___
*[`build.yaml` line 188 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyj_HGu4BlGOS7Z7bPb:-NyvjQmx8HbqdJtk_RI4:b-kxlxcz) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L188)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Yes basically just create necessary task files similar to the others in `DscResource.DocGenerator`. If you have time with that please do now or later, you decide. It is only this and SqlServerDsc that uses it I think.
</blockquote></details>

If there is an existing issue for this then mention me in it. If not if you create one with some pointers I'll get working on it. 

If it's not a big piece I'll work on it this week and then hopefully get that merged and then use the task from the `DocGenerator` repo here and not have to come back to it.
___
*[`source/en-US/ActiveDirectoryCSDsc.strings.psd1` line 10 at r3](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyutgfoDBuUDn3uj2Gq:-Nyvhf8F-Zy3YVHxFnDI:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/6294412256f05cfc2df82dc8aa32b8ac51b8c9c0/source/en-US/ActiveDirectoryCSDsc.strings.psd1#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think we need this:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-28 16:10 UTC, johlju reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-hughes)

___
*[`build.yaml` line 188 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-Nyj_HGu4BlGOS7Z7bPb:-NyzxnumC-oGB9GJKILR:b-igak44) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L188)):*
> If not if you create one with some pointers I'll get working on it.

I will try to do that tomorrow. 


<!-- Sent from Reviewable.io -->

2024-05-28 16:23 UTC, dan-hughes commented
@johlju 

I started the task [here](https://github.com/dsccommunity/DscResource.DocGenerator/commit/ecb14c12e4c1bb44090f02d4d6bb601a7e9bb7fb)

Ignoring the Tests am I heading the correct direction?

2024-05-28 17:10 UTC, johlju commented
Yes that looks okay to me 😊 Awesome work!

2024-05-31 17:50 UTC, dan-hughes commented
@johlju, can you look at this again?

With the `DocGenerator` changes and the tidy up I've just done, assuming the Class Resource work stays as 'preparation' work for any future resources, is there anything else?

2024-06-01 06:48 UTC, johlju commented
I think this is okay, will continue the review. I will first fix the bug in the task that fails. Build fails with:

```plaintext
New-ExternalHelp -Path 'D:\a\1\s\output\WikiContent' -OutputPath 'D:\a\1\s\output\builtModule\ActiveDirectoryCSDsc\5.1.0\en-US' -Force
ERROR: Cannot find path 'D:\a\1\s\output\builtModule\ActiveDirectoryCSDsc\5.1.0\en-US\ActiveDirectoryCSDsc-help.xml' because it does not exist.
``

I was expecting it could be issues with modules that still hasn't any public commands when we merged the meta task in DocGenerator. 🙂

2024-06-01 13:59 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-:-NzJ5D-G53oxo0gN8KdY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

___
*[`build.yaml` line 120 at r2](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryCSDsc/144#-NyjbddE8bqS9XHjOtk3:-NzJ5-Sj4xN8cO3ynEBl:b-m2mckm) ([raw file](https://github.com/dsccommunity/ActiveDirectoryCSDsc/blob/ac685c8c146582d7c532c0f232dd6ce6c6f71a7d/build.yaml#L120)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

As it's the 'future', to me it makes sense to leave any scaffolding for class based resources in place.

Unless it's worth just leaving it there commented out to it's easy to enable?
</blockquote></details>

We can leave it in.


<!-- Sent from Reviewable.io -->

2024-06-01 13:59 UTC, merged

2024-06-01 14:00 UTC, johlju commented
Awesome work on this. 🙂